# Generated by Django 4.1 on 2022-08-23 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_personnel', '0002_remove_education_qualifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID', primary_key=True, serialize=False)),
                ('delegation', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='командировочные в BYN: ')),
                ('limit_journey', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Лимит аванса на поездку в BYN: ')),
                ('limit_hotel', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Лимит аванса на гостинницу в BYN: ')),
                ('limit_payment_on_account', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Лимит аванса на день в BYN: ')),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_personnel.personnel', verbose_name='сотрудник')),
            ],
            options={
                'verbose_name': 'командировка',
                'verbose_name_plural': 'командировка',
                'ordering': ['id'],
            },
        ),
    ]
