# Generated by Django 4.1 on 2022-08-23 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_calendar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delegation',
            name='limit_hotel',
        ),
        migrations.RemoveField(
            model_name='delegation',
            name='limit_journey',
        ),
        migrations.RemoveField(
            model_name='delegation',
            name='limit_payment_on_account',
        ),
    ]
