# Generated by Django 4.1 on 2022-09-01 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('fathers_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество')),
                ('slug', models.SlugField(max_length=30, unique=True, verbose_name='URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d', verbose_name='фото сотрудника')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Мужчина'), ('F', 'Женшина')], max_length=1, null=True, verbose_name='Пол')),
                ('email', models.EmailField(blank=True, max_length=25, null=True, verbose_name='e-mail')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='телефон')),
                ('is_acceptance', models.BooleanField(default=True, verbose_name='Zatwierdzić')),
            ],
            options={
                'verbose_name': 'сотрудника',
                'verbose_name_plural': 'сотрудники',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('born', models.DateField(verbose_name='День рождения')),
                ('birth_place', models.CharField(max_length=50, verbose_name='Место рождения')),
                ('birth_country', models.CharField(max_length=50, verbose_name='Страна рождения')),
                ('country', models.CharField(max_length=50, verbose_name='Страна постоянного проживания')),
                ('city', models.CharField(max_length=50, verbose_name='Город постоянного проживания')),
                ('post_code', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Почтовый индекс')),
                ('street', models.CharField(max_length=100, verbose_name='Улица')),
                ('street_number', models.CharField(max_length=10, verbose_name='Номер дома')),
                ('house_number', models.CharField(max_length=10, verbose_name='Номер квартиры')),
                ('education', models.CharField(choices=[('PE', 'Начальное образование'), ('SE', 'Среднее образование'), ('HE', 'Высшее образование')], max_length=2, verbose_name='образование')),
                ('uploadedFile', models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d', verbose_name='скану документов')),
                ('uploadedFile_date', models.DateField(verbose_name='дата годности документа')),
                ('is_acceptance', models.BooleanField(default=True, verbose_name='Zatwierdzić')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_personnel.personnel', verbose_name='сотрудник')),
            ],
            options={
                'verbose_name': 'Личные данные',
                'verbose_name_plural': 'Личные данные',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.CharField(choices=[('CF', 'Трудовой договор на неопределенный срок'), ('CI', 'Срочный трудовой договор'), ('CA', 'Договор подряда'), ('MC', 'Договор на оказание услуги')], max_length=2, verbose_name='тип договора')),
                ('employment_date_beginning', models.DateField(verbose_name='дата начала работы')),
                ('employment_date_ending', models.DateField(verbose_name='дата окончания контракта')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Размер зар. п.')),
                ('uploadedFile', models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d', verbose_name='скану документов')),
                ('uploadedFile_date', models.DateField(blank=True, null=True, verbose_name='дата годности документа')),
                ('education_remarks', models.TextField(blank=True, null=True, verbose_name='замечания по образованию')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name=' срок устрониения')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_personnel.personnel', verbose_name='сотрудник')),
            ],
            options={
                'verbose_name': 'Трудоустройство',
                'verbose_name_plural': 'Трудоустройство',
                'ordering': ['id'],
            },
        ),
    ]
