# Generated by Django 4.1 on 2022-08-22 09:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('fathers_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d', verbose_name='фото сотрудника')),
                ('gender', models.CharField(choices=[('M', 'Мужчина'), ('F', 'Женшина')], max_length=1, verbose_name='Пол')),
                ('country', models.CharField(max_length=30, verbose_name='Страна')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('postal_code', models.IntegerField(verbose_name='Индекс')),
                ('street_name', models.CharField(max_length=100, verbose_name='улица')),
                ('street_number', models.IntegerField(verbose_name='№ дода')),
                ('email', models.EmailField(blank=True, max_length=25, null=True, verbose_name='e-mail')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='телефон')),
                ('is_acceptance', models.BooleanField(default=True, verbose_name='Zatwierdzić')),
            ],
            options={
                'verbose_name': 'сотрудника',
                'verbose_name_plural': 'сотрудники',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Superiors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='уровень')),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_company.orgstructure', verbose_name='подразделение фирмы')),
                ('superior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_personnel.personnel', verbose_name='начальник')),
            ],
            options={
                'verbose_name': 'список началников подразделении',
                'verbose_name_plural': 'список началников подразделении',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.CharField(choices=[('CF', 'Трудовой договор на неопределенный срок'), ('CI', 'Срочный трудовой договор'), ('CA', 'Договор подряда'), ('MC', 'Договор на оказание услуги')], max_length=2, verbose_name='тип договора')),
                ('employment_date_beginning', models.DateField(verbose_name='дата начала работы')),
                ('employment_date_ending', models.DateField(verbose_name='дата окончания контракта')),
                ('contract_for_an_indefinite_period', models.BooleanField(verbose_name=models.DateField(verbose_name='дата окончания контракта'))),
                ('salary', models.FloatField(verbose_name='Размер зар. п.')),
                ('uploadedFile', models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d', verbose_name='скану документов')),
                ('uploadedFile_date', models.DateField(verbose_name='дата годности документа')),
                ('education_remarks', models.TextField(blank=True, null=True, verbose_name='замечания по образованию')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name=' срок устрониения')),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_company.orgstructure', verbose_name='подразделение фирмы')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_personnel.personnel', verbose_name='сотрудник')),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_company.function', verbose_name='должность')),
            ],
            options={
                'verbose_name': 'Трудоустройство',
                'verbose_name_plural': 'Трудоустройство',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(choices=[('PE', 'Начальное образование'), ('SE', 'Среднее образование'), ('HE', 'Высшее образование')], max_length=2, verbose_name='образование')),
                ('uploadedFile', models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d', verbose_name='скану документов')),
                ('uploadedFile_date', models.DateField(verbose_name='дата годности документа')),
                ('is_acceptance', models.BooleanField(default=True, verbose_name='Zatwierdzić')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_personnel.personnel', verbose_name='сотрудник')),
                ('qualifications', models.ManyToManyField(blank=True, null=True, to='app_company.qualifications', verbose_name='Квалификации')),
            ],
            options={
                'verbose_name': 'образование сотрудника',
                'verbose_name_plural': 'образование сотрудники',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_personnel.superiors', verbose_name='начальник')),
                ('subordinate', models.ManyToManyField(to='app_personnel.personnel', verbose_name='подчиненный')),
            ],
            options={
                'verbose_name': 'список подчиненных',
                'verbose_name_plural': 'список подчиненных',
                'ordering': ['id'],
            },
        ),
    ]
