# Generated by Django 4.1 on 2022-08-23 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_personnel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='qualifications',
        ),
    ]
