# Generated by Django 4.1 on 2022-09-08 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(verbose_name='Дата начала отпуска')),
                ('date_end', models.DateField(verbose_name='Дата окончания отпуска')),
                ('is_acceptance', models.BooleanField(default=True, verbose_name='Согласовано')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_personnel.personnel', verbose_name='Сотрудник')),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отпуск',
                'verbose_name_plural': 'Отпуск',
                'ordering': ['date_start', 'is_acceptance'],
            },
        ),
    ]
