# Generated by Django 4.1 on 2022-08-22 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(max_length=150, verbose_name='должность')),
                ('education', models.CharField(choices=[('PE', 'Начальное образование'), ('SE', 'Среднее образование'), ('HE', 'Высшее образование')], max_length=2, verbose_name='Необходимое образование для должности')),
            ],
            options={
                'verbose_name': 'должность',
                'verbose_name_plural': 'должность',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrgStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departament', models.CharField(max_length=150, verbose_name='подразделение фирмы')),
            ],
            options={
                'verbose_name': 'подразделение фирмы',
                'verbose_name_plural': 'подразделение фирмы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Qualifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualifications', models.CharField(max_length=150, verbose_name='Квалификации')),
            ],
            options={
                'verbose_name': 'Квалификации',
                'verbose_name_plural': 'Квалификации',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacation_limit', models.IntegerField(default='20', verbose_name='отпуск')),
                ('remote_work_limit', models.IntegerField(default='0', verbose_name='удаленная работа')),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_company.function', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'отпуск и удаленная работа',
                'verbose_name_plural': 'отпуск',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delegation', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='командировочные в BYN: ')),
                ('limit_journey', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Лимит аванса на поездку в BYN: ')),
                ('limit_hotel', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Лимит аванса на гостинницу в BYN: ')),
                ('limit_payment_on_account', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Лимит аванса на день в BYN: ')),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_company.function')),
            ],
            options={
                'verbose_name': 'командировка',
                'verbose_name_plural': 'командировка',
                'ordering': ['id'],
            },
        ),
    ]
