# Generated by Django 4.1 on 2022-08-23 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_company', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Delegation',
        ),
    ]
